<?xml version="1.0" encoding="utf-8"?><Database Name="PERC_TEST_eCC" Class="sampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=uappecc;Initial Catalog=PERC_TEST_eCC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PERC_TEST_eCCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChecklistTemplateItems" Member="ChecklistTemplateItems">
    <Type Name="ChecklistTemplateItem">
      <Column Name="ChecklistTemplateItemCkey" Type="System.Decimal" DbType="Decimal(20,9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChecklistTemplateItemKey" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Namespace" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChecklistTemplateVersionCKey" Type="System.Decimal" DbType="Decimal(20,9) NOT NULL" CanBeNull="false" />
      <Column Name="LocalKey" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="LocalDisplayHTMLText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PrintOutHTMLText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="VisibleRTFText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EditorComment" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phase1ReviewApproval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Phase2ReviewApproval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Phase3ReviewApproval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Phase4ReviewApproval" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Reviewer1" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="Reviewer2" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="Reviewer3" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="Reviewer4" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="Released" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VisibleText" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="LongText" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ReportText" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ReportTypeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FormatTypeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DescriptionText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PopUpNoteHTML" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TextAfterConcept" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MetaData" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FSN" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ConceptID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GenericConceptID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LegacyCode" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SNOMED_MatchTypeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SNOMED_NeedsReview" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MinRepetitions" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MaxRepetitions" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ItemTypeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreviousItemCKey" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="ParentItemCKey" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="SourceCKey" Type="System.Decimal" DbType="Decimal(20,9) NOT NULL" CanBeNull="false" />
      <Column Name="PrevChecklistTemplateItemCkey" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="OrigChecklistTemplateItemCkey" Type="System.Decimal" DbType="Decimal(20,9) NOT NULL" CanBeNull="false" />
      <Column Name="BaseCkey" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="TemplateInjectionCkey" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="SubTreeTemplateInjectionCkey" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="SNOMEDinjectionCID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="AnswerDataTypeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnswerMaxChars" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnswerMaxDecimals" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnswerMaxValue" Type="System.Decimal" DbType="Decimal(18,9)" CanBeNull="true" />
      <Column Name="AnswerMinValue" Type="System.Decimal" DbType="Decimal(18,9)" CanBeNull="true" />
      <Column Name="AnswerUnits" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KeepWithNext" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AuthorityRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Required" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultDisabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Hidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorityValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SkipConcept" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ControlTypeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlTip" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SelectionDisablesChildren" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SelectionDisablesSiblings" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ItemDependencyType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ItemXValues" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ItemYKeys" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ValidationRule" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ValidationText" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ValidationFunction" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NAACCR_ItemNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAACCR_ItemName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="NAACCR_DisplayName" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="NAACCR_AnswerValue" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="NAACCR_AnswerKey" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="NAACCR_AnswerText" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="NAACCR_TempKey" Type="System.Decimal" DbType="Decimal(20,9)" CanBeNull="true" />
      <Column Name="ExtensionGroup" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ComboBoundColumn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComboLimitToList" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ComboColumnCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComboHeader" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ComboHeaderText" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ComboResizableCols" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ComboResizableRows" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ComboListRows" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComboListWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComboAutoExpand" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ComboCol1" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ComboCol2" Type="System.String" DbType="NVarChar(800) NOT NULL" CanBeNull="false" />
      <Column Name="ComboCol3" Type="System.String" DbType="NVarChar(800) NOT NULL" CanBeNull="false" />
      <Column Name="ComboCol4" Type="System.String" DbType="NVarChar(800) NOT NULL" CanBeNull="false" />
      <Column Name="ComboCol1Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComboCol2Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComboCol3Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComboCol4Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelLeft" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelTop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelBackColor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelBackStyle" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="LabelBorderStyle" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="LabelBorderColor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelBorderWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelFont" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LabelFontBold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LabelFontColor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LabelFontItalic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LabelFontSize" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="LabelFontUnderline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LabelTextAlign" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="ControlDataSource" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ControlRowSource" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" />
      <Column Name="ControlRowSourceType" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="ControlFormat" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ControlName" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ControlHeight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlLeft" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlTop" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlBackColor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlBackStyle" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="ControlBorderStyle" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="ControlBorderColor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlBorderWidth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlFont" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ControlFontBold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ControlFontColor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlFontItalic" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ControlFontSize" Type="System.Decimal" DbType="Decimal(3,1)" CanBeNull="true" />
      <Column Name="ControlFontUnderline" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ControlHelpContextID" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ControlRightClickMenu" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ControlTag" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="ControlTabStop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ControlTabIndex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ControlTextAlign" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="HL7_MSH" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="HL7_ORC" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="HL7_OBR" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="HL7_OBX_3_Qcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HL7_OBX_5_ACode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HL7_OBX_5_1_Text" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LOINC" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ICDO3Morph" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ICDO3Topo" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ICDO3Grade" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ICDO3Behav" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ICDO3MatchTypeKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ICDO3FullTerm" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="ICDO3NeedsReview" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ICD9" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ICD10" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CPT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HCPCS" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ATC" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AHFS" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="USP" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BeforeUpdate" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="AfterUpdate" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnChange" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnNotInList" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnExit" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnEnter" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnGotFocus" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnLostFocus" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnClick" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnDblClick" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnMouseDown" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnMouseMove" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnMouseUp" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnKeyDown" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnKeyUp" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="OnKeyPress" Type="System.String" DbType="NText" CanBeNull="true" />
      <Column Name="HelpFile" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="HTMLHelp" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" />
      <Column Name="TS" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="DeprecatedFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeprecatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="ChecklistTemplateItem_ChecklistTemplateItem" Member="ChecklistTemplateItems" ThisKey="ChecklistTemplateItemCkey" OtherKey="BaseCkey" Type="ChecklistTemplateItem" />
      <Association Name="ChecklistTemplateItem_ChecklistTemplateItem1" Member="ChecklistTemplateItem3" ThisKey="ChecklistTemplateItemCkey" OtherKey="ChecklistTemplateItemCkey" Type="ChecklistTemplateItem" Cardinality="One" />
      <Association Name="ChecklistTemplateItem_ChecklistTemplateItem2" Member="ChecklistTemplateItems1" ThisKey="ChecklistTemplateItemCkey" OtherKey="OrigChecklistTemplateItemCkey" Type="ChecklistTemplateItem" />
      <Association Name="ChecklistTemplateItem_ChecklistTemplateItem3" Member="ChecklistTemplateItems2" ThisKey="ChecklistTemplateItemCkey" OtherKey="ParentItemCKey" Type="ChecklistTemplateItem" />
      <Association Name="ChecklistTemplateItem_ChecklistTemplateItem" Member="ChecklistTemplateItem1" ThisKey="BaseCkey" OtherKey="ChecklistTemplateItemCkey" Type="ChecklistTemplateItem" IsForeignKey="true" />
      <Association Name="ChecklistTemplateItem_ChecklistTemplateItem1" Member="ChecklistTemplateItem2" ThisKey="ChecklistTemplateItemCkey" OtherKey="ChecklistTemplateItemCkey" Type="ChecklistTemplateItem" IsForeignKey="true" />
      <Association Name="ChecklistTemplateItem_ChecklistTemplateItem2" Member="ChecklistTemplateItem4" ThisKey="OrigChecklistTemplateItemCkey" OtherKey="ChecklistTemplateItemCkey" Type="ChecklistTemplateItem" IsForeignKey="true" />
      <Association Name="ChecklistTemplateItem_ChecklistTemplateItem3" Member="ChecklistTemplateItem5" ThisKey="ParentItemCKey" OtherKey="ChecklistTemplateItemCkey" Type="ChecklistTemplateItem" IsForeignKey="true" />
    </Type>
  </Table>
</Database>